import { Runeword } from "@/typings/runeword";

export const Runewords: Record<string, Runeword> = {
  stealth: {
    key: "stealth",
    runes: ["tal", "eth"],
    name: {
      es: "Sigilo",
      en: "Stealth",
    },
    level: {
      es: "Nv. 17",
      en: "Lv. 17",
    },
    apply_on: {
      es: ["Armaduras"],
      en: ["Armors"],
    },
    details: {
      es: [
        "Correr/andar un +25% más Rápido",
        "Velocidad de Lanzamiento un +25% más Rápido",
        "Recuperación de Golpe un +25% más Rápida",
        "+6 de Destreza",
        "+15% de Regeneración de maná",
        "+15 de Aguante Máximo",
        "+30% de Resistencia al Veneno",
        "Daño Mágico Reducido en 3 p.",
      ],
      en: [
        "Magic Damage Reduced By 3",
        "+6 To Dexterity",
        "+15 To Maximum Stamina",
        "Poison Resist +30%",
        "Regenerate Mana 15%",
        "25% Faster Run/Walk",
        "25% Faster Cast Rate",
        "25% Faster Hit Recovery",
      ],
    },
    references: {
      es: "https://diablo.fandom.com/wiki/Stealth_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Stealth_Rune_Word",
    },
  },
  leaf: {
    key: "leaf",
    runes: ["tir", "ral"],
    name: {
      es: "Hoja",
      en: "Leaf",
    },
    level: {
      es: "Nv. 19",
      en: "Lv. 19",
    },
    apply_on: {
      es: ["Bastones"],
      en: ["Staffs"],
    },
    details: {
      es: [
        "Añade 5-30 de Daño de Fuego",
        "+3 a las Habilidades de Fuego",
        "+3 para Descarga de fuego (solo Hechicera)",
        "+3 para Infierno (solo Hechicera)",
        "+3 para Calor (solo Hechicera)",
        "+2 al mana Tras Cada Muerte",
        "+2-198 de Defensa (+2 por Nivel)",
        "Resistencia al Frio +33%",
      ],
      en: [
        "Adds 5-30 Fire Damage",
        "+3 To Fire Skills",
        "+3 To Fire Bolt (Sorceress Only)",
        "+3 To Inferno (Sorceress Only)",
        "+3 To Warmth (Sorceress Only)",
        "+2 To Mana After Each Kill",
        "+ (2 Per Character Level) +2-198 To Defense (Based On Character Level)",
        "Cold Resist +33%",
      ],
    },
    references: {
      es: "https://diablo.fandom.com/wiki/Leaf_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Leaf_Rune_Word",
    },
  },
  zephyr: {
    key: "zephyr",
    runes: ["ort", "eth"],
    name: {
      es: "Céfiro",
      en: "Zephyr",
    },
    level: {
      es: "Nv. 21",
      en: "Lv. 21",
    },
    apply_on: {
      es: ["Arcos", "Ballestas"],
      en: ["Bows", "Crossbows"],
    },
    details: {
      es: [
        "+33% Daño Perfeccionado",
        "+66 Puntuación de Ataque",
        "Añade 1-50 de Daño de Relámpago",
        "-25% Defensa del Objetivo por Golpe",
        "+25 Defensa",
        "25% Correr/Andar Mas Rápido",
        "25% Velocidad de Ataque Aumentada",
        "7% Posibilidad de Lanzar el Nivel 1 Tornado al Recibir un Golpe",
      ],
      en: [
        "+33% Enhanced Damage",
        "+66 To Attack Rating",
        "Adds 1-50 Lightning Damage",
        "-25% Target Defense",
        "+25 Defense",
        "25% Faster Run/Walk",
        "25% Increased Attack Speed",
        "7% Chance To Cast Level 1 Twister When Struck",
      ],
    },
    references: {
      es: "https://diablo.fandom.com/wiki/Zephyr_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Zephyr_Rune_Word",
    },
  },
  chains_of_honor: {
    key: "chains_of_honor",
    runes: ["dol", "um", "ber", "ist"],
    name: {
      es: "Cadenas de Honor",
      en: "Chains of Honor",
    },
    level: {
      es: "Nv. 63",
      en: "Lv. 63",
    },
    apply_on: {
      es: ["Armaduras"],
      en: ["Armors"],
    },
    details: {
      es: [
        "+2 a Todas las Habilidades",
        "+200% Daño a Demonios",
        "+100% Daño a Muertos Vivientes",
        "8% Vida Robada por Impacto",
        "+70% Defensa Mejorada",
        "+20 de Fuerza",
        "Repostar Vida +7",
        "Todas las Resistencias +65",
        "Daño Reducido en 8%",
        "+25% de Probabilidad de Encontrar Objetos Mágicos",
      ],
      en: [
        "+2 To All Skills",
        "+200% Damage To Demons",
        "+100% Damage To Undead",
        "8% Life Stolen Per Hit",
        "+70% Enhanced Defense",
        "+20 To Strength",
        "Replenish Life +7",
        "All Resistances +65",
        "Physical Damage Received Reduced By 8%",
        "25% Better Chance of Getting Magic Items",
      ],
    },
    references: {
      es: "https://diablo.fandom.com/wiki/Chains_of_Honor_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Chains_of_Honor_Rune_Word",
    },
  },
  call_to_arms: {
    key: "call_to_arms",
    runes: ["amn", "ral", "mal", "ist", "ohm"],
    name: {
      es: "Llamado a las Armas",
      en: "Call to Arms",
    },
    level: {
      es: "Nv. 51",
      en: "Lv. 51",
    },
    apply_on: {
      es: ["Armas"],
      en: ["Weapons"],
    },
    details: {
      es: [
        "+1 a Todas las Habilidades",
        "+40% Velocidad de Ataque aumentada",
        "+250-290% Daño Mejorado (varia)",
        "Añade 5-30 Daño de Fuego",
        "7% Vida Robada por Impacto",
        "+2-6 a Instrucción de Batalla (varia)",
        "+1-6 a Ordenes de Batalla (varia)",
        "+1-4 a Grito de Batalla (varia)",
        "Evita la Curación del Monstruo",
        "Repostar Vida +12",
        "+30% de Probabilidad de Encontrar Objetos Mágicos",
      ],
      en: [
        "+1 To All Skills",
        "+40% Increased Attack Speed",
        "+250-290% Enhanced Damage",
        "Adds 5-30 Fire Damage",
        "7% Life Stolen Per Hit",
        "+2-6 To Battle Command",
        "+1-6 To Battle Orders",
        "+1-4 To Battle Cry",
        "Prevent Monster Heal",
        "Replenish Life +12",
        "30% Better Chance of Getting Magic Items",
      ],
    },
    references: {
      es: "https://diablo.fandom.com/wiki/Call_to_Arms_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Call_to_Arms_Rune_Word",
    },
  },
  strength: {
    key: "strength",
    runes: ["amn", "tir"],
    name: {
      es: "Fuerza",
      en: "Strength",
    },
    level: {
      es: "Nv. 25",
      en: "Lv. 25",
    },
    apply_on: {
      es: ["Armas Melee"],
      en: ["Melee Weapons"],
    },
    details: {
      es: [
        "+35% Daño Mejorado",
        "25% Posibilidad de Golpe Triturador",
        "7% Vida Robada Por Impacto",
        "+20 Fuerza",
        "+10 Vitalidad",
        "+2 al mana Tras Cada Muerte",
      ],
      en: [
        "35% Enhanced Damage",
        "+25% Chance Of Crushing Blow",
        "7% Life Stolen Per Hit",
        "+2 To Mana After Each Kill",
        "+20 To Strength",
        "+10 To Vitality",
      ],
    },
    references: {
      es: "https://diablo.fandom.com/wiki/Strength_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Strength_Rune_Word",
    },
  },
  fortitude: {
    key: "fortitude",
    runes: ["el", "sol", "dol", "lo"],
    name: {
      es: "Fortaleza",
      en: "Fortitude",
    },
    level: {
      es: "Nv. 59",
      en: "Lv. 59",
    },
    apply_on: {
      es: ["Armaduras", "Armas"],
      en: ["Armors", "Weapons"],
    },
    details_on: [
      {
        key: "weapon",
        name: {
          es: "Arma",
          en: "Weapon",
        },
        items: {
          es: [
            "20% de Posibilidades de Lanzar el Nivel 15 Armadura Gélida al recibir un Azote",
            "+25% Velocidad de Lanzamiento Mayor",
            "+300% Daño Mejorado",
            "+9 al Daño Mínimo",
            "+50 de Puntuación de Ataque",
            "+20% Azote Mortal",
            "El Impacto hace que el Monstruo Huya 25%",
            "+200% Defensa Perfeccionada",
            "+XX de vida [1 a 1.5 por Nivel] (varia)",
            "Todas las resistencias +20-30 (varia)",
            "12% el Daño Infligido Repercute en el Mana",
            "+1 al Radio de Luz",
          ],
          en: [
            "20% Chance To Cast Level 15 Chilling Armor when Struck",
            "+25% Faster Cast Rate",
            "+300% Enhanced Damage",
            "+200% Enhanced Defense",
            "+XX To Life (Based on Character Level) (varies)",
            "All Resistances +25-30 (varies)",
            "12% Damage Taken Goes To Mana",
            "+1 To Light Radius",
            "+9 To Minimum Damage",
            "+50 To Attack Rating",
            "20% Deadly Strike",
            "Hit Causes Monster To Flee 25%",
          ],
        },
      },
      {
        key: "armor",
        name: {
          es: "Armadura",
          en: "Armor",
        },
        items: {
          es: [
            "20% de Posibilidades de Lanzar el Nivel 15 Armadura Gélida al recibir un Azote",
            "+25% Velocidad de Lanzamiento Mayor",
            "+300% Daño Mejorado",
            "+200% Defensa Perfeccionada",
            "+15 Defensa",
            "+XX de vida [1 a 1.5 por Nivel] (varia)",
            "Repostar vida +7",
            "5% a la Resistencia Máxima a los Relámpagos",
            "Todas las resistencias +20-30 (varia)",
            "Daño reducido por 7",
            "12% el Daño Infligido Repercute en el Mana",
            "+1 al Radio de Luz",
          ],
          en: [
            "20% Chance To Cast Level 15 Chilling Armor when Struck",
            "+25% Faster Cast Rate",
            "+300% Enhanced Damage",
            "+200% Enhanced Defense",
            "+XX To Life (Based on Character Level) (varies)",
            "All Resistances +25-30 (varies)",
            "12% Damage Taken Goes To Mana",
            "+1 To Light Radius",
            "+15 Defense",
            "Replenish Life +7",
            "+5% To Maximum Lightning Resist",
            "Damage Reduced By 7",
          ],
        },
      },
    ],
    references: {
      es: "https://diablo.fandom.com/wiki/Fortitude_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Fortitude_Rune_Word",
    },
  },
  lore: {
    key: "lore",
    runes: ["ort", "sol"],
    name: {
      es: "Acervo",
      en: "Lore",
    },
    level: {
      es: "Nv. 27",
      en: "Lv. 27",
    },
    apply_on: {
      es: ["Yelmos"],
      en: ["Helmets"],
    },
    details: {
      es: [
        "+1 a Todos los Niveles de Habilidad",
        "+10 de Energía",
        "+2 al mana Tras Cada Muerte",
        "Resistencia a los Rayos +30%",
        "Daño Reducido en 7",
        "+2 al Radio de Luz",
      ],
      en: [
        "+1 To All Skill Levels",
        "+10 To Energy",
        "+2 To Mana After Each Kill",
        "Lightning Resist +30%",
        "Damage Reduced By 7",
        "+2 To Light Radius",
      ],
    },
    references: {
      es: "https://diablo.fandom.com/wiki/Lore_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Lore_Rune_Word",
    },
  },
  holy_thunder: {
    key: "holy_thunder",
    runes: ["eth", "ral", "ort", "tal"],
    name: {
      es: "Trueno Sagrado",
      en: "Holy Thunder",
    },
    level: {
      es: "Nv. 21",
      en: "Lv. 21",
    },
    apply_on: {
      es: ["Cetros"],
      en: ["Scepters"],
    },
    details: {
      es: [
        "+60% Daño Mejorado",
        "5% Resistencia Máxima a los Rayos",
        "+75 Daño de Veneno Durante 5 Segundos",
        "Añade 5-30 Daño de Fuego",
        "Añade 21-110 Daño de Relámpago",
        "+10 al Daño Máximo",
        "-25% a la Defensa del Objetivo",
        "Resistencia a los Rayos +60%",
        "+3 para Golpe Sagrado (Solo Paladín)",
        "Nivel 7 Cadena de Rayos (60 Cargas)",
      ],
      en: [
        "+60% Enhanced Damage",
        "-25% Target Defense",
        "5-30 Fire Damage",
        "21-110 Lightning Damage",
        "+75 Poison Damage for 5 seconds",
        "+10 to Maximum Damage",
        "+60% Lightning Resist",
        "+5 to Maximum Lightning Resist",
        "+3 to Holy Shock (Paladin only)",
        "Level 7 Chain Lightning (60 charges)",
      ],
    },
    references: {
      es: "https://diablo.fandom.com/wiki/Holy_Thunder_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Holy_Thunder_Rune_Word",
    },
  },
  rhyme: {
    key: "rhyme",
    runes: ["shael", "eth"],
    name: {
      es: "Rima",
      en: "Rhyme",
    },
    level: {
      es: "Nv. 29",
      en: "Lv. 29",
    },
    apply_on: {
      es: ["Escudos"],
      en: ["Shields"],
    },
    details: {
      es: [
        "Velocidad de Bloqueo un +40% más Rápido",
        "+20% de Probabilidad de Bloqueo",
        "15% de Regeneración de Maná",
        "+25 a Todas las Resistencias",
        "No Te Pueden Congelar",
        "+50% de Oro Extra de los Monstruos",
        "+25% de Probabilidad de Encontrar Objetos Mágicos",
      ],
      en: [
        "20% Increased Chance of Blocking",
        "40% Faster Block Rate",
        "+25 to All Resistances",
        "Regenerate Mana 15%",
        "Cannot Be Frozen",
        "50% Extra Gold From Monsters",
        "25% Better Chance Of Getting Magic Items",
      ],
    },
    references: {
      es: "https://diablo.fandom.com/wiki/Rhyme_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Rhyme_Rune_Word",
    },
  },
  rift: {
    key: "rift",
    runes: ["hel", "ko", "lem", "gul"],
    name: {
      es: "Grieta",
      en: "Rift",
    },
    level: {
      es: "Nv. 53",
      en: "Lv. 53",
    },
    apply_on: {
      es: ["Armas de Asta", "Cetros"],
      en: ["Polearms", "Scepters"],
    },
    details: {
      es: [
        "20% de Posibilidades de Lanzar el Nivel 16 Tornado al Azotar",
        "16% de Posibilidades de Lanzar el Nivel 21 Orbe Helado al Atacar",
        "20% de Bonificación en el Ataque",
        "Añade 160-250 de Daño Mágico",
        "Añade 60-180 de Daño de Fuego",
        "+5-10 a Todos los Atributos (varia)",
        "+10 de Destreza",
        "38% el Daño Infligido Repercute en el Mana",
        "75% Oro Extra de los Monstruos",
        "Nivel 15 de Doncella de Hierro (40 Cargas)",
        "Requisitos -20%",
      ],
      en: [
        "20% Chance To Cast Level 16 Tornado On Striking",
        "16% Chance To Cast Level 21 Frozen Orb On Attack",
        "20% Bonus To Attack Rating",
        "Adds 160-250 Magic Damage",
        "Adds 60-180 Fire Damage",
        "+5-10 To All Stats (varies)",
        "+10 To Dexterity",
        "38% Damage Taken Goes To Mana",
        "75% Extra Gold From Monsters",
        "Level 15 Iron Maiden (40 Charges)",
        "Requirements -20%",
      ],
    },
    references: {
      es: "https://diablo.fandom.com/wiki/Rift_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Rift_Rune_Word",
    },
  },
  white: {
    key: "white",
    runes: ["dol", "io"],
    name: {
      es: "Blancura",
      en: "White",
    },
    level: {
      es: "Nv. 35",
      en: "Lv. 35",
    },
    apply_on: {
      es: ["Varas"],
      en: ["Wands"],
    },
    details: {
      es: [
        "El Impacto Hace que el Monstruo Huya 25%",
        "+10 Vitalidad",
        "+3 Para las Habilidades de Veneno y Hueso (Solo Nigromante)",
        "+3 Para Armadura de Huesos (Solo Nigromante)",
        "+2 Para Lanza Osea (Solo Nigromante)",
        "+4 Para Dominio de los Esqueletos (Solo Nigromante)",
        "Daño de Magia Reducido en 4",
        "20% Velocidad de Lanzamiento Mayor",
        "+13 de Mana",
      ],
      en: [
        "Hit Causes Monster To Flee +25%",
        "+10 To Vitality",
        "+3 To Poison and Bone Spells (Necromancer Only)",
        "+3 To Bone Armor (Necromancer Only)",
        "+2 To Bone Spear (Necromancer Only)",
        "+4 To Skeleton Mastery (Necromancer Only)",
        "Magic Damage Reduced By 4",
        "20% Faster Cast Rate",
        "+13 To Mana",
      ],
    },
    references: {
      es: "https://diablo.fandom.com/wiki/White_Rune_Word",
      en: "https://diablo.fandom.com/wiki/White_Rune_Word",
    },
  },
  insight: {
    key: "insight",
    runes: ["ral", "tir", "tal", "sol"],
    name: {
      es: "Perspicacia",
      en: "Insight",
    },
    level: {
      es: "Nv. 27",
      en: "Lv. 27",
    },
    apply_on: {
      es: ["Armas de Asta", "Bastones", "Arcos", "Balletas"],
      en: ["Polearms", "Staffs", "Bows", "Crossbows"],
    },
    details: {
      es: [
        "Aura Meditación de Nivel 12-17 si está Equipado (varia)",
        "Velocidad de Lanzamiento un +35% más Rápido",
        "+200-260% de Daño Mejorado (varia)",
        "+9 p. de Daño Mínimo",
        "+180-250% de Bonus al Índice de Ataque (varia)",
        "Añade 5-30 p. de Daño de Fuego",
        "+75 p. de Daño de Veneno Durante 5 s",
        "+1-6 a Azote Crítico (varia)",
        "+5 a Todos los Atributos",
        "+2 p. de Maná tras Cada Asesinato",
        "+23% de Probabilidad de Encontrar Objetos Mágicos",
      ],
      en: [
        "Level 12-17 Meditation Aura When Equipped",
        "+35% Faster Cast Rate",
        "+200-260% Enhanced Damage (varies)",
        "+9 To Minimum Damage",
        "180-250% Bonus to Attack Rating",
        "Adds 5-30 Fire Damage",
        "+75 Poison Damage Over 5 Seconds",
        "+1-6 To Critical Strike",
        "+5 To All Attributes",
        "+2 To Mana After Each Kill",
        "23% Better Chance of Getting Magic Items",
      ],
    },
    references: {
      es: "https://diablo.fandom.com/wiki/Insight_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Insight_Rune_Word",
    },
  },
  duress: {
    key: "duress",
    runes: ["shael", "um", "thul"],
    name: {
      es: "Coaccion",
      en: "Duress",
    },
    level: {
      en: "Nv. 47",
      es: "Lv. 47",
    },
    apply_on: {
      es: ["Armaduras"],
      en: ["Armors"],
    },
    details: {
      es: [
        "+40% Recuperación de Impacto Mas Rápida",
        "+10-20% Daño Mejorado",
        "Añade 37-133 Daño de Frio (Duración 2 Segundos)",
        "15% Posibilidad de Golpe Triturador",
        "33% Posibilidad de Heridas Abiertas",
        "+150-200% Defensa Perfeccionada (varia)",
        "20% Drenaje de Resistencia mas lento",
        "Resistencia al Frio +45%",
        "Resistencia al Rayo +15%",
        "Resistencia al Fuego +15%",
        "Resistencia al Veneno +15%",
      ],
      en: [
        "+40% Faster Hit Recovery",
        "+10-20% Enhanced Damage",
        "Adds 37-133 Cold Damage 2 sec. Duration (Normal)",
        "15% Chance of Crushing Blow",
        "33% Chance of Open Wounds",
        "+150-200% Enhanced Defense",
        "-20% Slower Stamina Drain",
        "Cold Resist +45%",
        "Lightning Resist +15%",
        "Fire Resist +15%",
        "Poison Resist +15%",
      ],
    },
    references: {
      es: "https://diablo.fandom.com/wiki/Duress_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Duress_Rune_Word",
    },
  },
  smoke: {
    key: "smoke",
    runes: ["nef", "lum"],
    name: {
      es: "Humo",
      en: "Smoke",
    },
    level: {
      es: "Nv. 37",
      en: "Lv. 37",
    },
    apply_on: {
      es: ["Armaduras"],
      en: ["Armors"],
    },
    details: {
      es: [
        "+75% Defensa Perfeccionada",
        "Todas las Resistencias +50%",
        "+280 Defensa Contra Misil",
        "20% Recuperación de Impacto Mas Rápida",
        "Nivel 6 Debilitar (18 Cargas)",
        "+10 de Energía",
        "-1 al Radio de Luz",
      ],
      en: [
        "+75% Enhanced Defense",
        "+280 Defense vs. Missiles",
        "All Resistances +50",
        "20% Faster Hit Recovery",
        "Level 6 Weaken (18 Charges)",
        "+10 To Energy",
        "-1 To Light Radius",
      ],
    },
    references: {
      es: "https://diablo.fandom.com/wiki/Smoke_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Smoke_Rune_Word",
    },
  },
  fury: {
    key: "fury",
    runes: ["jah", "gul", "eth"],
    name: {
      es: "Furia",
      en: "Fury",
    },
    level: {
      es: "Nv. 65",
      en: "Lv. 65",
    },
    apply_on: {
      es: ["Armas Melee"],
      en: ["Melee Weapons"],
    },
    details: {
      es: [
        "+40% Velocidad de Ataque Aumentada",
        "+209% Daño Mejorado",
        "Ignorar Defensa del Objetivo",
        "-25% Defensa del Objetivo",
        "20% de Bonificación en el Ataque",
        "6% Vida Robada por Impacto",
        "33% Azote Mortal",
        "66% Posibilidad de Heridas Abiertas",
        "Evita la Curación del Monstruo",
        "+5 Para Frenesí (solo Bárbaro)",
      ],
      en: [
        "+209% Enhanced Damage",
        "40% Increased Attack Speed",
        "Prevent Monster Heal",
        "66% Chance of Open Wounds",
        "33% Chance of Deadly Strike",
        "-25% Target Defense",
        "20% to Attack Rating",
        "6% Life Stolen Per Hit",
        "Ignores Target Defense",
        "+5 to Frenzy (Barbarian only)",
      ],
    },
    references: {
      es: "https://diablo.fandom.com/wiki/Fury_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Fury_Rune_Word",
    },
  },
  beast: {
    key: "beast",
    runes: ["ber", "tir", "um", "mal", "lum"],
    name: {
      es: "Bestia",
      en: "Beast",
    },
    level: {
      es: "Nv. 63",
      en: "Lv. 63",
    },
    apply_on: {
      es: ["Martillos", "Cetros", "Hachas"],
      en: ["Hammers", "Scepters", "Axes"],
    },
    details: {
      es: [
        "Nivel 9 Aura Fanatismo Cuando esta Equipado",
        "+40% Velocidad de Ataque aumentada",
        "+240-270% Daño Mejorado (varia)",
        "20% Posibilidad de Golpe Triturador",
        "25% Posibilidad de Heridas Abiertas",
        "+3 a Hombre Oso",
        "+3 a Licantropía",
        "Evita la Curación del Monstruo",
        "+25-40 de Fuerza (varia)",
        "+10 de Energía",
        "+2 mana Tras Cada Muerte",
        "Nivel 13 Invoca al Oso Pardo (5 Cargas)",
      ],
      en: [
        "Level 9 Fanaticism Aura When Equipped",
        "+40% Increased Attack Speed",
        "+240-270% Enhanced Damage",
        "+20% Chance of Crushing Blow",
        "+25% Chance of Open Wounds",
        "+3 To Werebear",
        "+3 To Lycanthropy",
        "Prevent Monster Heal",
        "+25-40 To Strength",
        "+10 To Energy",
        "+2 To Mana After Each Kill",
        "Level 13 Summon Grizzly (5 Charges)",
      ],
    },
    references: {
      es: "https://diablo.fandom.com/wiki/Beast_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Beast_Rune_Word",
    },
  },
  honor: {
    key: "honor",
    runes: ["amn", "el", "ith", "tir", "sol"],
    name: {
      es: "Honor",
      en: "Honor",
    },
    level: {
      es: "Nv. 27",
      en: "Lv. 27",
    },
    apply_on: {
      es: ["Armas Melee"],
      en: ["Melee Weapons"],
    },
    details: {
      es: [
        "+160% Daño Mejorado",
        "+9 al Daño Mínimo",
        "+9 al Daño Máximo",
        "25% Azote Mortal",
        "+250 de Puntuación de Ataque",
        "+1 a Todos los Niveles de Habilidad",
        "7% Vida Robada por Impacto",
        "Repostar Vida +10",
        "+10 Fuerza",
        "+1 al Radio de Luz",
        "+2 al mana Tras Cada Muerte",
      ],
      en: [
        "+160% Enhanced Damage",
        "+9 to Minimum Damage",
        "+9 to Maximum Damage",
        "+25% Deadly Strike",
        "+250 to Attack Rating",
        "+1 to All Skills",
        "7% Life Stolen per Hit",
        "+10 Replenish Life",
        "+10 to Strength",
        "+1 to Light Radius",
        "+2 to Mana per Kill",
      ],
    },
    references: {
      es: "https://diablo.fandom.com/wiki/Honor_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Honor_Rune_Word",
    },
  },
  enigma: {
    key: "enigma",
    runes: ["jah", "ith", "ber"],
    name: {
      es: "Enigma",
      en: "Enigma",
    },
    level: {
      es: "Nv. 65",
      en: "Lv. 65",
    },
    apply_on: {
      es: ["Armaduras"],
      en: ["Armors"],
    },
    details: {
      es: [
        "+2 a Todas las Habilidades",
        "+45% Correr/Andar Mas Rápido",
        "+1 para Teletransporte",
        "+750-775 Defensa (varia)",
        "+0-74 de Fuerza (0.75 por Nivel)",
        "Aumenta la Vida Máxima 5%",
        "Daño Reducido en 8%",
        "+14 Vida Tras Cada Muerte",
        "15% Daño Infligido Repercute en el mana",
        "+1-99% de Probabilidad de Encontrar Objetos Mágicos [1 por Nivel]",
      ],
      en: [
        "+2 To All Skills",
        "+45% Faster Run/Walk",
        "+1 To Teleport",
        "+750-775 Defense",
        "+0-74 To Strength (Based On Character Level)",
        "Increase Maximum Life 5%",
        "Physical Damage Received Reduced By 8%",
        "+14 Life After Each Kill",
        "15% Damage Taken Goes To Mana",
        "+1-99% Better Chance of Getting Magic Items (Based On Character Level)",
      ],
    },
    references: {
      es: "https://diablo.fandom.com/wiki/Enigma_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Enigma_Rune_Word",
    },
  },
  infinity: {
    key: "infinity",
    runes: ["ber", "mal", "ber", "ist"],
    name: {
      es: "Infinito",
      en: "Infinity",
    },
    level: {
      es: "Nv. 63",
      en: "Lv. 63",
    },
    apply_on: {
      es: ["Armas de Asta", "Lanzas"],
      en: ["Polearms", "Lances"],
    },
    details: {
      es: [
        "50% de Lanzar Nivel 20 Cadena de Rayos al Matar un Monstruo",
        "Nivel 12 Aura Convicción Cuando esta Equipado",
        "+35% Correr/Andar mas Rápido",
        "+255-325% Daño Mejorado (varia)",
        "-(45-55)% para Resistencia al Rayo Enemigo",
        "40% Posibilidad de Golpe Triturador",
        "Evita la Curación del Monstruo",
        "+0-49 de Vitalidad (+0.5 por Nivel)",
        "+30% de Probabilidad de Encontrar Objetos Mágicos",
        "Nivel 21 Armadura Ciclón (30 Cargas)",
      ],
      en: [
        "50% Chance To Cast Level 20 Chain Lightning When You Kill An Enemy",
        "Level 12 Conviction Aura When Equipped",
        "+35% Faster Run/Walk",
        "+255-325% Enhanced Damage",
        "-(45-55)% To Enemy Lightning Resist",
        "+40% Chance of Crushing Blow",
        "Prevent Monster Heal",
        "0.5-49.5 To Vitality (Based on Character Level)",
        "30% Better Chance of Getting Magic Items",
        "Level 21 Cyclone Armor (30 Charges)",
      ],
    },
    references: {
      es: "https://diablo.fandom.com/wiki/Infinity_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Infinity_Rune_Word",
    },
  },
  spirit: {
    key: "spirit",
    runes: ["tal", "thul", "ort", "amn"],
    name: {
      es: "Espíritu",
      en: "Spirit",
    },
    level: {
      es: "Nv. 25",
      en: "Lv. 25",
    },
    apply_on: {
      es: ["Espadas", "Escudos"],
      en: ["Swords", "Shields"],
    },
    details_on: [
      {
        key: "sword",
        name: {
          es: "Espada",
          en: "Sword",
        },
        items: {
          es: [
            "+2 a todas las habilidades",
            "+(25-35)% Velocidad de Lanzamiento mas rápido (varia)",
            "+55% Recuperación de Impacto mas rápido",
            "Añade 1-50 Daño Relámpago",
            "Añade 3-14 Daño de Frio",
            "+75 Daño de Veneno Durante 5 Segundos",
            "7% Vida Robada por Impacto",
            "+250 Defensa contra Misiles",
            "+22 de Vitalidad",
            "+(89-112) de Mana (varia)",
            "+(3-8) Absorción de Magia (varia)",
          ],
          en: [
            "+2 To All Skills",
            "+25-35% Faster Cast Rate (varies)",
            "+55% Faster Hit Recovery",
            "+250 Defense vs. Missiles",
            "+22 To Vitality",
            "+89-112 To Mana (varies)",
            "+3-8 Magic Absorb (varies)",
            "+75 Poison Damage Over 5 Seconds",
            "Adds 3-14 Cold Damage",
            "Adds 1-50 Lightning Damage",
            "7% Life Stolen Per Hit",
          ],
        },
      },
      {
        key: "shield",
        name: {
          es: "Escudo",
          en: "Shield",
        },
        items: {
          es: [
            "+2 a Todas las Habilidades",
            "+(25-35)% Velocidad de Lanzamiento mas Rápido (varia)",
            "+55% Recuperación de Impacto mas Rápido",
            "+250 Defensa contra Misiles",
            "+22 de Vitalidad",
            "+(89-112) de Mana (varia)",
            "Resistencia a los Rayos 35%",
            "Resistencia al Frio 35%",
            "Resistencia al Veneno 35%",
            "+(3-8) Absorción de Magia (varia)",
            "El Atacante Recibe el Daño de 14",
          ],
          en: [
            "+2 To All Skills",
            "+25-35% Faster Cast Rate (varies)",
            "+55% Faster Hit Recovery",
            "+250 Defense vs. Missiles",
            "+22 To Vitality",
            "+89-112 To Mana (varies)",
            "+3-8 Magic Absorb (varies)",
            "Poison Resist +35%",
            "Cold Resist +35%",
            "Lightning Resist +35%",
            "Attacker Takes Damage of 14",
          ],
        },
      },
    ],
    references: {
      es: "https://diablo.fandom.com/wiki/Spirit_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Spirit_Rune_Word",
    },
  },
  grief: {
    key: "grief",
    runes: ["eth", "tir", "lo", "mal", "ral"],
    name: {
      es: "Dolor",
      en: "Grief",
    },
    level: {
      es: "Nv. 59",
      en: "Lv. 59",
    },
    apply_on: {
      es: ["Hachas", "Espadas"],
      en: ["Axes", "Swords"],
    },
    details: {
      es: [
        "35% de Posibilidades de Lanzar el Nivel 15 Veneno al Recibir un Azote",
        "+30-40% Velocidad de Ataque Aumentada (varia)",
        "+340-400 Daño (varia)",
        "Ignorar Defensa del Objetivo",
        "-25% Defensa del Objetivo",
        "+1-185% Daño a Demonios (+1.875 por Nivel)",
        "Añade 5-30 Daño de Fuego",
        "-20-25% para Resistencia al Veneno Enemigo (varia)",
        "20% Azote Mortal",
        "Evita la Curación del Monstruo",
        "+2 al mana Tras Cada Muerte",
        "+10-15 Vida después de Cada Muerte",
      ],
      en: [
        "35% Chance To Cast Level 15 Venom On Striking",
        "+30-40% Increased Attack Speed",
        "Damage +340-400",
        "Ignore Target's Defense",
        "-25% Target Defense",
        "+(1.875 per character level) 1.875-185.625% Damage To Demons (Based on Character Level)",
        "Adds 5-30 Fire Damage",
        "-(20-25)% To Enemy Poison Resist",
        "+20% Deadly Strike",
        "Prevent Monster Heal",
        "+2 To Mana After Each Kill",
        "+10-15 Life After Each Kill",
      ],
    },
    references: {
      es: "https://diablo.fandom.com/wiki/Grief_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Grief_Rune_Word",
    },
  },
  delirium: {
    key: "delirium",
    runes: ["lem", "ist", "io"],
    name: {
      es: "Delirio",
      en: "Delirium",
    },
    level: {
      es: "Nv. 51",
      en: "Lv. 51",
    },
    apply_on: {
      es: ["Yelmos"],
      en: ["Helmets"],
    },
    details: {
      es: [
        "1% Posibilidad de Lanzar el Nivel 50 Delirio al Recibir un Azote",
        "6% Posibilidad de Lanzar el Nivel 14 Ráfaga de Mente al Recibir un Azote",
        "14% Posibilidad de Lanzar el Nivel 13 Terror al Recibir un Azote",
        "11% Posibilidad de Lanzar el Nivel 18 Confundir al Azotar",
        "+2 a Todas las Habilidades",
        "+261 Defensa",
        "+10 de Vitalidad",
        "50% Oro Extra de los Monstruos",
        "+25% de Probabilidad de Encontrar Objetos Mágicos",
        "Nivel 17 Atracción (60 Cargas)",
      ],
      en: [
        "1% Chance To Cast Level 50 Delirium When Struck (morph)",
        "6% Chance To Cast Level 14 Mind Blast When Struck",
        "14% Chance To Cast Level 13 Terror When Struck",
        "11% Chance To Cast Level 18 Confuse On Striking",
        "+2 To All Skills",
        "+261 Defense",
        "+10 To Vitality",
        "50% Extra Gold From Monsters",
        "25% Better Chance of Getting Magic Items",
        "Level 17 Attract (60 Charges)",
      ],
    },
    references: {
      es: "https://diablo.fandom.com/wiki/Delirium_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Delirium_Rune_Word",
    },
  },
} as const;
